#include "project.h"
#include "display.h"
#include "ports.h"
#include "clock.h"
#include "date.h"
#include "user.h"
#include "timezone.h"

/* Offsets are stored in half-hours internally, but are always presented to
   the user as real hours (e.g. +1, +5.5, -3.5). */
s8 PrimaryUtcOffsetHalfHours = 2;   /* UTC+1 default for Central Europe */
s8 SecondUtcOffsetHalfHours = 16;  /* UTC+8 default */

/* Keep the timezone/DST interpretation independent from the legacy clock
   correction state.  This flag is synchronized when the clock setup is
   saved. */
u8 TimeZoneDstEnabled = 0;

static s16 wrap_day_minutes(s16 m)
{
    while (m < 0) m += 1440;
    while (m >= 1440) m -= 1440;
    return m;
}

static u8 last_sunday_of_month(u8 days)
{
    u8 dow_last = (u8)((sDate.DayOfWeek + (days - sDate.day)) % 7);
    return (u8)(days - dow_last);
}

void timezone_set_dst_enabled(u8 enabled)
{
    TimeZoneDstEnabled = enabled ? 1 : 0;
}

u8 timezone_is_dst_active(void)
{
    u8 d;

    if (!TimeZoneDstEnabled) return 0;

    /* EU daylight-saving rule used by the Chronos firmware:
       last Sunday in March through last Sunday in October. */
    if (sDate.month < 3 || sDate.month > 10) return 0;
    if (sDate.month > 3 && sDate.month < 10) return 1;

    if (sDate.month == 3)
    {
        d = last_sunday_of_month(31);
        if (sDate.day > d) return 1;
        if (sDate.day < d) return 0;
        return (sTime.hour >= 3);
    }

    d = last_sunday_of_month(31);
    if (sDate.day < d) return 1;
    if (sDate.day > d) return 0;
    return (sTime.hour < 3);
}

s16 timezone_get_utc_minutes(void)
{
    s16 m = (s16)sTime.hour * 60 + sTime.minute;

    /* PrimaryUtcOffsetHalfHours describes STANDARD time, e.g. MEZ = UTC+1.
       If DLR/DST is enabled and currently active, the displayed local clock
       is one additional hour ahead and that hour must also be removed. */
    m -= (s16)PrimaryUtcOffsetHalfHours * 30;
    if (timezone_is_dst_active()) m -= 60;

    return wrap_day_minutes(m);
}

s16 timezone_get_bmt_minutes(void)
{
    return wrap_day_minutes((s16)(timezone_get_utc_minutes() + 60));
}

s16 timezone_get_second_minutes(void)
{
    return wrap_day_minutes((s16)(timezone_get_utc_minutes() +
                                  (s16)SecondUtcOffsetHalfHours * 30));
}

void display_timezone_offset(u8 segments, u32 value, u8 digits, u8 blanks)
{
    s32 sv = (s32)value;
    u16 halfhours;
    u16 hours;
    (void)segments;
    (void)digits;
    (void)blanks;

    halfhours = (u16)((sv < 0) ? -sv : sv);
    hours = halfhours / 2u;

    clear_line(LINE1);

    if (halfhours & 1u)
    {
        /* Display x.5. The arrow generated by set_value() remains the sign. */
        u16 t = (u16)(hours * 10u + 5u);
        display_chars(LCD_SEG_L1_3_1, chronos_itoa(t, 3, 1), SEG_ON);
        display_symbol(LCD_SEG_L1_DP1, SEG_ON);
    }
    else
    {
        display_chars(LCD_SEG_L1_1_0, chronos_itoa(hours, 2, 1), SEG_ON);
        display_symbol(LCD_SEG_L1_DP1, SEG_OFF);
    }
}

void display_timezone2(u8 line, u8 update)
{
    s16 m;
    u8 hh, mm, ss;
    u8 t[7];
    (void)line;

    if (update == DISPLAY_LINE_CLEAR)
    {
        display_symbol(LCD_SEG_L2_COL1, SEG_OFF_BLINK_OFF);
        display_symbol(LCD_SEG_L2_COL0, SEG_OFF_BLINK_OFF);
        return;
    }
    if (update != DISPLAY_LINE_UPDATE_FULL &&
        update != DISPLAY_LINE_UPDATE_PARTIAL) return;

    m = timezone_get_second_minutes();
    hh = (u8)(m / 60);
    mm = (u8)(m % 60);
    ss = sTime.second;

    t[0] = (u8)('0' + hh / 10u);
    t[1] = (u8)('0' + hh % 10u);
    t[2] = (u8)('0' + mm / 10u);
    t[3] = (u8)('0' + mm % 10u);
    t[4] = (u8)('0' + ss / 10u);
    t[5] = (u8)('0' + ss % 10u);
    t[6] = 0;

    display_chars(LCD_SEG_L2_5_0, t, SEG_ON);
    display_symbol(LCD_SEG_L2_COL1, SEG_ON);
    display_symbol(LCD_SEG_L2_COL0, SEG_ON);
}

void mx_timezone2(u8 line)
{
    s32 v = SecondUtcOffsetHalfHours;
    (void)line;

    clear_display_all();
    display_chars(LCD_SEG_L2_4_2, (u8 *)"TZ2", SEG_ON);
    set_value(&v, 3, 0, -24, 28,
              SETVALUE_ROLLOVER_VALUE + SETVALUE_DISPLAY_VALUE +
              SETVALUE_DISPLAY_ARROWS + SETVALUE_NEXT_VALUE,
              LCD_SEG_L1_3_0, display_timezone_offset);
    SecondUtcOffsetHalfHours = (s8)v;
    button.all_flags = 0;
}
